language: java
jdk: oraclejdk8
sudo: false # faster builds

install: true
script: mvn install -Dmaven.javadoc.skip=true -B -V
script: mvn cobertura:cobertura

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)